server:
 port: 8082
 
spring:
  application:
    name: usuario
    
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hubmarket-usuario
    username: postgres
    password: admin 
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:  
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true  
    generate-ddl: true

  
cors:
  allowed-origins: http://localhost:8080 