server:
  port: 8095
  context-path: /auth
 
spring:
  application:
    name: auth
      
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hubmarket-usuario
    username: postgres
    password: admin 

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true  


security:   
  oauth2:
    client:
#      access-token-validity-seconds: 1800
      authorized-grant-types: password,refresh_token,authorization_code,implicit
      client-id: web
      client-secret: 12345
#      resource-ids: resources
      scope: password
