server:
 port: 8080 

spring:
 application:
  name: apigateway
  
zuul:
 prefix: /api
 routes:  
  produto:
   path: /produto/**
   serviceId: produto
  usuario:
   path: /usuario/**
   serviceId: usuario
