spring:
 application:
  name: apigateway
  
server:
 port: 8081 
  
zuul:
 prefix: /api/v1
 routes: 
  produto:
   path: /produto/**
   serviceId: produto
  pedido:
   path: /pedido/**
   serviceId: pedido