spring:
 application:
  name: apigateway
  
server:
 port: 8080 
  
zuul:
 prefix: /api
 routes:  
  produto:
   path: /produto/**
   serviceId: produto

security:
  oauth2:     
    client:
      accessTokenUri: http://localhost:8095/oauth/token
      userAuthorizationUri: http://localhost:8095/oauth/authorize
      clientId: web
      clientSecret: 12345
    resource:
      userInfoUri: http://localhost:8095/auth/