spring:
 application:
  name: apigateway
  
server:
 port: 8081 
  
zuul:
 prefix: /api
 routes:  
  auth:
   path: /auth/**
   sensitiveHeaders:
   serviceId: auth
  produto:
   path: /produto/**
   serviceId: produto


#security:
#  oauth2:     
#    client:
#      accessTokenUri: http://localhost:8080/api/auth/oauth/token
#      userAuthorizationUri: http://localhost:8080/api/auth/oauth/authorize
#      clientId: web
#      clientSecret: 12345
#    resource:
#      userInfoUri: http://localhost:8080/api/auth/user