server:
 port: 8083
 
spring:
  application:
    name: produto
    
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hubmarket-produto
    username: postgres
    password: admin 
    
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:  
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true  
    generate-ddl: true

cors:
  allowed-origins: http://localhost:8080 
  
#  jackson:
#    serialization:
#      fail-on-empty-beans: false
